version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
    restart: on-failure:3 
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_account
      - POSTGRES_PASSWORD=django_account
      - POSTGRES_DB=django_account_dev
    restart: on-failure:3
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    restart: on-failure:3
  redis:
    image: redis:alpine
    restart: on-failure:3
  celery:
    build: ./app
    command: celery -A django_account worker -l info
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis
    restart: on-failure:3
  celery-beat:
    build: ./app
    command: celery -A django_account beat -l info
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis
    restart: on-failure:3

volumes:
  postgres_data: